name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: compilar o programa principal
        run: gcc fibonacci.c function_fibonacci.c -o fibonacci

      - name: executar o programa principal
        run: ./fibonacci 9

      - name: mostrar o conteudo do arquivo criado
        run: cat fibonacci.txt

      - name: compilar o arquivo de teste
        run: gcc test_fibonacci.c function_fibonacci.c -o test_fibonacci

      - name: executar o arquivo de teste
        run: ./test_fibonacci
